// resources/js/routes.ts
const Ziggy = {
  url: "http://127.0.0.1:8000",
  port: 8000,
  defaults: {},
  routes: {
    "login": { uri: "login", methods: ["GET","HEAD"] },
    "login.store": { uri: "login", methods: ["POST"] },
    "register": { uri: "register", methods: ["GET","HEAD"] },
    "register.store": { uri: "register", methods: ["POST"] },
    "password.request": { uri: "forgot-password", methods: ["GET","HEAD"] },
    "password.email": { uri: "forgot-password", methods: ["POST"] },
    "dashboard": { uri: "dashboard", methods: ["GET","HEAD"] },
    "logout": { uri: "logout", methods: ["POST"] },
    "profile": { uri: "profile", methods: ["GET","HEAD"] },
    "profile.update": { uri: "profile", methods: ["PATCH"] },
    "profile.destroy": { uri: "profile", methods: ["DELETE"] },
    "users.index": { uri: "users", methods: ["GET","HEAD"] },
    "users.create": { uri: "users/create", methods: ["GET","HEAD"] },
    "users.store": { uri: "users", methods: ["POST"] },
    "users.show": { uri: "users/{user}", methods: ["GET","HEAD"] },
    "users.edit": { uri: "users/{user}/edit", methods: ["GET","HEAD"] },
    "users.update": { uri: "users/{user}", methods: ["PUT","PATCH"] },
    "users.destroy": { uri: "users/{user}", methods: ["DELETE"] },
    "projects.index": { uri: "projects", methods: ["GET","HEAD"] },
    "projects.create": { uri: "projects/create", methods: ["GET","HEAD"] },
    "projects.store": { uri: "projects", methods: ["POST"] },
    "projects.show": { uri: "projects/{project}", methods: ["GET","HEAD"] },
    "projects.edit": { uri: "projects/{project}/edit", methods: ["GET","HEAD"] },
    "projects.update": { uri: "projects/{project}", methods: ["PUT","PATCH"] },
    "projects.destroy": { uri: "projects/{project}", methods: ["DELETE"] },
    "projects.sprints.index": { uri: "projects/{project}/sprints", methods: ["GET","HEAD"] },
    "projects.sprints.create": { uri: "projects/{project}/sprints/create", methods: ["GET","HEAD"] },
    "projects.sprints.store": { uri: "projects/{project}/sprints", methods: ["POST"] },
    "projects.sprints.show": { uri: "projects/{project}/sprints/{sprint}", methods: ["GET","HEAD"] },
    "projects.sprints.edit": { uri: "projects/{project}/sprints/{sprint}/edit", methods: ["GET","HEAD"] },
    "projects.sprints.update": { uri: "projects/{project}/sprints/{sprint}", methods: ["PUT","PATCH"] },
    "projects.sprints.destroy": { uri: "projects/{project}/sprints/{sprint}", methods: ["DELETE"] },
    "projects.sprints.tasks.index": { uri: "projects/{project}/sprints/{sprint}/tasks", methods: ["GET","HEAD"] },
    "projects.sprints.tasks.create": { uri: "projects/{project}/sprints/{sprint}/tasks/create", methods: ["GET","HEAD"] },
    "projects.sprints.tasks.store": { uri: "projects/{project}/sprints/{sprint}/tasks", methods: ["POST"] },
    "projects.sprints.tasks.show": { uri: "projects/{project}/sprints/{sprint}/tasks/{task}", methods: ["GET","HEAD"] },
    "projects.sprints.tasks.edit": { uri: "projects/{project}/sprints/{sprint}/tasks/{task}/edit", methods: ["GET","HEAD"] },
    "projects.sprints.tasks.update": { uri: "projects/{project}/sprints/{sprint}/tasks/{task}", methods: ["PUT","PATCH"] },
    "projects.sprints.tasks.destroy": { uri: "projects/{project}/sprints/{sprint}/tasks/{task}", methods: ["DELETE"] },
    "projects.tasks.index": { uri: "projects/{project}/tasks", methods: ["GET","HEAD"] },
    "projects.tasks.create": { uri: "projects/{project}/tasks/create", methods: ["GET","HEAD"] },
    "projects.tasks.store": { uri: "projects/{project}/tasks", methods: ["POST"] },
    "projects.tasks.show": { uri: "projects/{project}/tasks/{task}", methods: ["GET","HEAD"] },
    "projects.tasks.edit": { uri: "projects/{project}/tasks/{task}/edit", methods: ["GET","HEAD"] },
    "projects.tasks.update": { uri: "projects/{project}/tasks/{task}", methods: ["PUT","PATCH"] },
    "projects.tasks.destroy": { uri: "projects/{project}/tasks/{task}", methods: ["DELETE"] },
    // ...dst...
  },
};

export default Ziggy;
