// resources/js/ziggy.ts
// Ziggy route definitions generated by Laravel
const Ziggy = {
  url: "http://127.0.0.1:8000",
  port: 8000,
  defaults: {},
  routes: {
    "debugbar.openhandler": { uri: "_debugbar/open", methods: ["GET", "HEAD"] },
    "debugbar.clockwork": { uri: "_debugbar/clockwork/{id}", methods: ["GET", "HEAD"], parameters: ["id"] },
    "login": { uri: "login", methods: ["GET", "HEAD"] },
    "login.store": { uri: "login", methods: ["POST"] },
    "logout": { uri: "logout", methods: ["POST"] },
    "register": { uri: "register", methods: ["GET", "HEAD"] },
    "register.store": { uri: "register", methods: ["POST"] },
    "dashboard": { uri: "dashboard", methods: ["GET", "HEAD"] },
    "home": { uri: "/", methods: ["GET", "HEAD"] },
    "password.request": { uri: "forgot-password", methods: ["GET", "HEAD"] },
    "password.email": { uri: "forgot-password", methods: ["POST"] },
    // tambahkan route lain sesuai kebutuhan...
  },
};

// Hindari error TypeScript "Property 'Ziggy' does not exist on type 'Window'"
declare global {
  interface Window {
    Ziggy?: typeof Ziggy;
  }
}

// Gabungkan Ziggy bawaan window jika ada
if (typeof window !== "undefined" && window.Ziggy) {
  Object.assign(Ziggy.routes, window.Ziggy.routes);
}

export { Ziggy };
